### ISSUE TITLE
Update GitLab Runner to Java 11

### ISSUE THREAD

**Issue by VictorPrins** [SERG-Delft/jpacman#31]
In one of our tests, we used the Java 11 [`Optional.isEmpty()`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Optional.html#isEmpty()) method. Our builds and tests succeeded locally, but after pushing the GitLab jobs failed. The reason for this probably is that the GitLab Runner uses an older version of Java, as `Optional.isEmpty()` was introduced in Java 11. By checking out [this Docker image](https://hub.docker.com/r/tudsqte/ci-image), which from inspection of the `.gitlab-ci.yml` appears to be the image used by our GitLab runner, we found out that this image runs Java 9. Since we are receiving code updates to Java 11 often lately, we expected the runner to be running Java 11 as well. 
For the time being, the semantically equivalent `!Optional.isPresent()` can be used to achieve the same results. Can you, however, update the GitLab Runner to Java 11?

**Comment by casperboone** [comment]
Hi Victor,

Thanks for reporting this. We're working on a new version of the Docker image. We'll probably not change this for all students, but you'll be able to manually enable it after it's available :).

**Comment by casperboone** [comment]
The java version in the Docker image has been updated :)
